name: Open-CE Feedstock Merge Triggers

author: "Open-CE"

description: "Tasks to be completed at merge time for Open-CE feedstocks."

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y conda-build
    - name: Create Version Branch
      shell: bash -l {0}
      run: |
        echo "If the package version changed from the last commit to this"
        echo "one, a new branch will be created for the previous version"
        echo "from the last commit."
        open_ce_path="$GITHUB_ACTION_PATH/../../../"
        pip install -e ${open_ce_path}
        python ${open_ce_path}/git_tools/create_version_branch.py \
                  --branch_if_changed
