name: Open-CE Feedstock Merge Triggers

author: "Open-CE"

description: "Tasks to be completed at merge time for Open-CE feedstocks."

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y conda-build
    - name: Clone build tools
      shell: bash -l {0}
      run: |
        git clone https://github.com/open-ce/open-ce-builder.git \
                  ./open-ce-builder
    - name: Create Version Branch
      shell: bash -l {0}
      run: |
        echo "If the package version changed from the last commit to this"
        echo "one, a new branch will be created for the previous version"
        echo "from the last commit."
        pip install -e open-ce-builder/open_ce
        python open-ce-builder/git_tools/create_version_branch.py \
                  --branch_if_changed
