name: Open-CE Feedstock PR Required Tests

author: "Open-CE"

description: "Required global PR tests for Open-CE feedstocks."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: open-ce/open-ce-environments
        path: ./open-ce-environments
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y conda-build
    - name: Check Dependencies
      shell: bash -l {0}
      run: |
        # Validate all env files with the new feedstock.
        open_ce_path="$GITHUB_ACTION_PATH/../../../open-ce"
        env_path="./open-ce-environments/envs"
        python ${open_ce_path}/open-ce validate config \
                                       ${env_path}/*-env.yaml \
                                       --build_types cuda,cpu \
                                       --repository_folder ../
