name: Open-CE Feedstock PR Required Tests

author: "Open-CE"

description: "Required global PR tests for Open-CE feedstocks."

runs:
  using: "composite"
  steps:
    - name: PR Test Placeholder
      shell: bash -l {0}
      run: echo "No required tests added yet."
