name: Open-CE Feedstock PR Required Tests

author: "Open-CE"

description: "Required global PR tests for Open-CE feedstocks."

runs:
  using: "composite"
  steps:
    - name: Install dependencies and set envrionment
      shell: bash -l {0}
      run: |
        conda install -y conda-build
        echo "env_path=$GITHUB_ACTION_PATH/../../../envs" >> $GITHUB_ENV
    - name: Check Dependencies
      shell: bash -l {0}
      run: |
        # Validate the open-ce env file
        git clone https://github.com/open-ce/open-ce-builder.git \
                  ./open-ce-builder
        pip install -e open-ce-builder
        open-ce validate config \
                         ${env_path}/*-env.yaml \
                         --build_types cuda,cpu \
                         --python_versions 3.6,3.7,3.8 \
                         --repository_folder ../
    - name: Check recipes
      shell: bash -l {0}
      run: |
        python open-ce-builder/tests/feedstock_tests/check_recipes.py \
               --conda_build_config \
               "${env_path}/conda_build_config.yaml"
