#!/usr/bin/env python
"""
*****************************************************************
Licensed Materials - Property of IBM
(C) Copyright IBM Corp. 2020. All Rights Reserved.
US Government Users Restricted Rights - Use, duplication or
disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*****************************************************************
"""

import sys
import argparse
import utils
from errors import OpenCEError, Error
import build_env
import test_feedstock

def make_parser():
    ''' Parser for input arguments '''
    parser = utils.make_parser([], description = 'Open-CE Tool')

    subparsers = parser.add_subparsers(title='subcommands',
                                       description='valid subcommands',
                                       required=True)

    build_env_parser = subparsers.add_parser('build_env', parents=[build_env.make_parser()], add_help=False, help="build_env help")
    build_env_parser.set_defaults(func=build_env.build_env)

    test_feedstock_parser = subparsers.add_parser('test_feedstock', parents=[test_feedstock.make_parser()], add_help=False, help="test_feedstock help")
    test_feedstock_parser.set_defaults(func=test_feedstock.test_feedstock)

    return parser

def _main(arg_strings=None):
    parser = make_parser()
    args = parser.parse_args(arg_strings)
    args.func(args)
    return 0

if __name__ == '__main__':
    try:
        _main()
    except OpenCEError as err:
        print(err.msg, file=sys.stderr)
        sys.exit(1)

    sys.exit(0)
