name: Open-CE Feedstock PR Optional Tests

author: "Open-CE"

description: "Optional global PR tests for Open-CE feedstocks."

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y python=3.10 conda-build=3.22
    - name: Clone build tools
      shell: bash -l {0}
      run: |
        git clone https://github.com/open-ce/open-ce-builder.git \
                  ./open-ce-builder
    - name: Run PR Tests
      shell: bash -l {0}
      run: |
        pip install -e open-ce-builder
        open_ce_path="$GITHUB_ACTION_PATH/../../../"
        python open-ce-builder/tests/feedstock_tests/check_build_numbers.py \
               --conda_build_config \
               "${open_ce_path}/envs/conda_build_config.yaml"
