name: Open-CE Feedstock PR Optional Tests

author: "Open-CE"

description: "Optional global PR tests for Open-CE feedstocks."

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y conda-build
    - name: Clone build tools
      shell: bash -l {0}
      run: |
        git clone https://github.com/open-ce/open-ce-builder.git \
                  ./open-ce-builder
    - name: Run PR Tests
      shell: bash -l {0}
      run: |
        pip install -e open-ce-builer/open_ce
        python open-ce-builder/tests/feedstock_tests/check_build_numbers.py \
               --conda_build_config \
               "$root_path/envs/conda_build_config.yaml"
