name: Open-CE Feedstock PR Optional Tests

author: "Open-CE"

description: "Optional global PR tests for Open-CE feedstocks."

runs:
  using: "composite"
  steps:
    - name: Run PR Tests
      shell: bash -l {0}
      run: echo "No optional tests added yet."
