{% set name = "open-ce" %}
{% set version = "1.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - git_url: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - conda-build
    - pyyaml
    - requests
    - jinja2
    - python

test:
  commands:
    - open-ce -h
    - open-ce build env -h
    - open-ce build feedstock -h
    - open-ce build image -h
  imports:
    - open_ce
    - open_ce.build_env
    - open_ce.build_feedstock
    - open_ce.container_build
    - open_ce.build_image

about:
  home: https://github.com/open-ce/open-ce
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Open-CE tools for building feedstocks'
  description: |
      Open-CE tools package provides the common controlling collection of
      configuration and build scripts which are foundational to building 
      the underlying software component packages (feedstocks) which comprise
      the greater Open-CE package ecosystem.
  doc_url: https://github.com/open-ce/open-ce
  dev_url: https://github.com/open-ce/open-ce

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
