abseil_cpp:
  - 20200923
absl_py:
  - 0.12.*
arrow:
  - 3.0.0
astunparse:
  - 1.6
attrs:
  - 19
autoconf:
  - 2.69
automake:
  - 1.16
av:
  - 8.*
bazel:
  - 3.7.*
boost:
  - 1.67.0  # [not s390x]
  - 1.65.*  # [s390x]
c_compiler_version:
  - 7.2.*                      # [x86_64]
  - 7.3.*                      # [ppc64le]
  - 7.5.*                      # [s390x]
catalogue:
  - 2.*
cffi:
  - 1.14.*
click:
  - 7.*
cloudpickle:
  - 1.3.*
cmake:
  - 3.14.* # [not s390x]
  - 3.18.* # [s390x]
contextvars:
  - 2.4
coverage:
  - 4.*
cudnn:
  - 7.6.5.*                    # [cudatoolkit == '10.2']
  - 8.0.4.*                    # [cudatoolkit == '11.0']
cxx_compiler_version:
  - 7.2.*                      # [x86_64]
  - 7.3.*                      # [ppc64le]
cxxfilt:
  - 0.2.*
cymem:
  - 2.0.*
cython:
  - 0.29
cython_blis:
  - 0.4.*
dataclasses:
  - 0.7
dm_tree:
  - 0.1.*
eigen:
  - 3.3.7
ffmpeg:
  - 4.2.*
flatbuffers:
  - 1.12.*
freetype:
  - 2
fortran_compiler_version:
  - 7.2.*                      # [x86_64]
  - 7.3.*                      # [ppc64le]
fsspec:
  - 0.8.*
future:
  - 0.18.*
gast:
  - 0.4.0
git:
  - 2.15
google_auth:
  - 1.23.*
google_auth_oauthlib:
  - 0.4.*
google_pasta:
  - 0.2
googleapis_common_protos:
  - 1.52.*
graphsurgeon:
  - 0.4.1                     # [cudatoolkit == '10.2']
  - 0.4.5                     # [cudatoolkit == '11.0']
grpc_cpp:
  - 1.36.*
grpcio:
  - 1.35.*
harfbuzz:
  - 1.8
# Note: hdf5 version must be compatible with h5py
hdf5:
  - 1.10.4
hypothesis:
  - 5.*
h5py:
  - 2.10.0
importlib_resources:
  - 3.3.0
jasper:
  - 2.0.14
joblib:
  - 0.17
jpeg:
  - 9b
jpegturbo:
  - 2.1.0
keras_applications:
  - 1.0.8
keras_preprocessing:
  - 1.1.*
leveldb:
  - 1.20.*
libevent:
  - 2.1.*
libgcc:
  - 9.1.*                      # [x86_64]
  - 8.2.*                      # [ppc64le]
  - 8.4.*                      # [s390x]
libstdcxx:
  - 9.1.*                      # [x86_64]
  - 8.2.*                      # [ppc64le]
  - 8.4.*                      # [s390x]
libgfortran:
  - 7.2.*                      # [x86_64]
  - 7.3.*                      # [ppc64le]
libogg:
  - 1.3.*
libopus:
  - 1.3.*
libpng:
  - 1.6
libtiff:
  - 4.2
libtool:
  - 2.4.6
libvorbis:
  - 1.3.7
lmdb:
  - 0.9.*
magma:
  - 2.5.4.*
make:
  - 4.2.1
markdown:
  - 3.3.3
mock:
  - 3.*
murmurhash:
  - 1.0.*
nasm:                          # [x86_64]
  - 2.13.03                    # [x86_64]
networkx:
  - 2.*
ninja:
  - 1.10.*
nccl:
  - 2.8.*
numactl:
  - 2.0.*
numpy:
  - 1.19.*
onnx:
  - 1.7.*
onnx_graphsurgeon:
  - 0.2.*
openblas:
  - 0.3.6.*
opencv:
  - 3.4.14.*
openjdk:
  - 8.0.152                    # [x86_64]
  - 1.8.0                      # [ppc64le]
openmpi:
  - 4.1.1
opt_einsum:
  - 3.3.0
pathy:
  - 0.5.*
pillow:
  - 8.*
pip:
  - 20*
pkg_config:
  - 0.29.2
preshed:
  - 3.0.*
protobuf:
  - 3.14.*
psutil:
  - 5
pydantic:
  - 1.7.*
pytest:
  - 5.*
python:
  - 3.6 # [not s390x]
  - 3.7
pytorch:
  - 1.8.*
pytorch_lightning:
  - 1.2.*
pyyaml:
  - 5.*
requests:
  - 2.*
regex:
  - 2020.11.*
rust_nightly:
  - 1.53.0
scipy:
  - 1.*
sentencepiece:
  - 0.1.91
setuptools:
  - 50.3.* # [not s390x]
  - 51.*   # [s390x]
setuptools_rust:
  - 0.11.3
six:
  - 1.15.0
smart_open:
  - 2.2.*
spacy_legacy:
  - 3.0.5
srsly:
  - 2.*
tabulate:
  - 0.8.*
tensorboard:
  - 2.5.*
tensorboard_data_server:
  - 0.6.*
tensorboard_plugin_wit:
  - 1.6
tensorflow:
  - 2.5.*
tensorflow_hub:
  - 0.12
tensorrt:
  - 7.0.*                    # [cudatoolkit == '10.2']
  - 7.2.*                    # [cudatoolkit == '11.0']
termcolor:
  - 1.1.0
thinc:
  - 8.0.3
tokenizers:
  - 0.10.1
torchmetrics:
  - 0.3.*
torchtext:
  - 0.9.*
torchvision:
  - 0.9.*
tqdm:
  - 4.*
typer:
  - 0.3.2
typing_extensions:
  - 3.7.4.*
uff:
  - 0.6.5                    # [cudatoolkit == '10.2']
  - 0.6.9                    # [cudatoolkit == '11.0']
unzip:
  - 6.0
wasabi:
  - 0.8.1
werkzeug:
  - 1.*
wheel:
  - 0.35*
wrapt:
  - 1.12.*
zlib:
  - 1.2.11
zstd:
  - 1.4.*
