ppc_arch:
  - p10
cpu_opt_arch:
  - power9                  # [ppc64le]
cpu_opt_tune:
  - power10                 # [ppc64le]
vector_settings:
  - no-pcrel                # [ppc64le]
git_tag_for_env: open-ce-v1.11.2
