build_type:
  - cpu
_libarchive_static_for_cph:
  - 3.3.*
_libgcc_mutex:
  - 0.1
abseil_cpp:
  - 20200923.*
apipkg:
  - 1.5
arrow:
  - 3.0.*
asn1crypto:
  - 1.4.*
astor:
  - 0.8.*
autoconf:
  - 2.69
automake:
  - 1.16.*
aws_c_common:
  - 0.5.*
aws_c_event_stream:
  - 0.1.*
aws_checksums:
  - 0.1.*
aws_sdk_cpp:
  - 1.8.*
bazel:
  - 3.1.*
beautifulsoup4:
  - 4.9.*
binutils:
  - 2.33.*
bison:
  - 3.7
boost:
  - 1.65.*
brotli:
  - 1.0.*
brotlipy:
  - 0.7.*
bzip2:
  - 1.0.*
c_ares:
  - 1.17.*
c_compiler_version:
  - 7.5.*
ca_certificates:
  - 2021.4.*
certifi:
  - 2020.12.5.*
cffi:
  - 1.14.*
chardet:
  - 4.0.*
cmake:
  - 3.18.*
cmake_no_system:
  - 3.16.*
conda:
  - 4.9.*
conda_build:
  - 3.21.*
conda_package_handling:
  - 1.6.*
constructor:
  - 2.3.*
coverage:
  - 5.3.*
crosstool_ng:
  - 1.24.0*
cryptography:
  - 3.3.*
curl:
  - 7.71.*
cxx_compiler_version:
  - 7.5.*
cython:
  - 0.29.*
docutils:
  - 0.15.*
double_conversion:
  - 3.1.*
expat:
  - 2.2.*
flatbuffers:
  - 1.12.*
flex:
  - 2.6.*
freetype:
  - 2.10.*
gawk:
  - 5.1.*
gettext:
  - 0.21.*
gflags:
  - 2.2.*
git:
  - 2.23.*
gmp:
  - 6.1.*
glog:
  - 0.4.*
grpc_cpp:
  - 1.37.*
help2man:
  - 1.47.*
icu:
  - 68.1
idna:
  - 2.10
iso8601:
  - 0.1.*
jpeg:
  - 9b
krb5:
  - 1.18.*
lcms2:
  - 2.12
libarchive:
  - 3.4.*
libedit:
  - 3.1
libev:
  - 4.33
libevent:
  - 2.1.*
libffi:
  - 3.3.*
libgcc:
  - 8.4
libstdcxx:
  - 8.4
libidn2:
  - 2.3.*
libpng:
  - 1.6.*
libssh2:
  - 1.9.*
libtiff:
  - 4.2.*
libtool:
  - 2.4.*
libunistring:
  - 0.9.*
libuv:
  - 1.40.*
libxml2:
  - 2.9.*
lz4_c:
  - 1.9.*
m4:
  - 1.4.*
make:
  - 4.2.*
markupsafe:
  - 1.1.*
mock:
  - 4.0.*
mpmath:
  - 1.1.*
ncurses:
  - 6.2
nghttp2:
  - 1.41.*
ninja:
  - 1.10.*
nose:
  - 1.3.*
numpy:
  - 1.19.*
numpy_metapackage:
  - 1.19.*
openblas:
  - 0.3.*
openjdk:
  - 1.8.*
openssl:
  - 1.*
pandas:
  - 1.2.*
patch:
  - 2.7.*
patchelf:
  - 0.12
pcre:
  - 8.44
perl:
  - 5.26.*
pillow:
  - 8.2.*
pip:
  - 20*
pkg_config:
  - 0.29.*
#pkgconfig:
#  - 1.4.*
pkginfo:
  - 1.6.*
pluggy:
  - 0.13.*
pretend:
  - 1.0.*
protobuf:
  - 3.14.*
psutil:
  - 5
pybind11:
  - 2.5.*
pycosat:
  - 0.6.*
pycrypto:
  - 2.6.*
pycryptodome:
  - 3.9.*
pyinstaller:
  - 3.6
pyopenssl:
  - 20.0.*
pysocks:
  - 1.7.*
pytest:
  - 6.2.*
python:
  - 3.7
  - 3.8
python_libarchive_c:
  - 2.9
pyyaml:
  - 5.3.*
rapidjson:
  - 1.1.*
re2:
  - 2020.*
readline:
  - 8.0
requests:
  - 2.24.*
rhash:
  - 1.4.*
ruamel:
  - 1.0
ruamel_yaml:
  - 0.15.*
ruamel_yaml_clib:
  - 0.2.*
scandir:
  - 1.10.*
scikit_learn:
  - 0.23.*
scipy:
  - 1.5.*
setuptools:
  - 51*
snappy:
  - 1.1.*
sqlite:
  - 3.35.*
swig:
  - 3.0.*
termcolor:
  - 1.1.*
texinfo:
  - 6.5
tk:
  - 8.6.*
tqdm:
  - 4.47.*
unzip:
  - 6.0
uriparser:
  - 0.9.*
utf8proc:
  - 2.6.*
waf:
  - 2.0.*
wget:
  - 1.20.*
wrapt:
  - 1.12.*
xz:
  - 5.2.*
yaml:
  - 0.1.*
zip:
  - 3.0
zlib:
  - 1.2.*
zstd:
  - 1.4.*

#"Below packages belong to noarch"

altgraph:
  - 0.17.*
astunparse:
  - 1.6.*
atomicwrites:
  - 1.4.*
attrs:
  - 19.3.*
cached_property:
  - 1.5.*
conda_mirror:
  - 0.8.*
cryptography_vectors:
  - 2.8.*
execnet:
  - 1.7.*
filelock:
  - 3.0.*
flit:
  - 3.0.*
gast:
  - 0.3.*
glob2:
  - 0.7.*
google_pasta:
  - 0.2.*
hypothesis:
  - 6.*
importlib_metadata:
  - 1.7.*
jinja2:
  - 2.11.*
joblib:
  - 0.16.*
libx11_common_rhel7_s390x:
  - 1.6.*
libx11_devel_rhel7_s390x:
  - 1.6.*
libx11_rhel7_s390x:
  - 1.6.*
libxau_devel_rhel7_s390x:
  - 1.0.*
libxau_rhel7_s390x:
  - 1.0.*
libxcb_rhel7_s390x:
  - 1.13.*
macholib:
  - 1.11.*
more_itertools:
  - 8.4.*
nomkl:
  - 1.0.*
olefile:
  - 0.46.*
opt_einsum:
  - 3.1.0
orc:
  - 1.6.*
packaging:
  - 20.4.*
pbr:
  - 5.4.*
py:
  - 1.8.*
pycparser:
  - 2.20.*
pygments:
  - 2.7.*
pyparsing:
  - 2.4.*
pytest_runner:
  - 5.3.*
pytest_catchlog:
  - 1.2.*
pytest_cov:
  - 2.8.*
pytest_forked:
  - 1.1.*
pytest_mock:
  - 3.1.*
pytest_xdist:
  - 1.32.*
python_dateutil:
  - 2.8.*
pytoml:
  - 0.1.*
pytz:
  - 2020.1.*
setuptools_scm:
  - 3.2.*
six:
  - 1.15.*
soupsieve:
  - 2.2.*
sysroot_linux_s390x:
  - 2.17.*
threadpoolctl:
  - 2.1.*
thrift:
  - 0.13.*
typing_extensions:
  - 3.7.4.*
tzdata:
  - 2020*
urllib3:
  - 1.25.*
wcwidth:
  - 0.2.*
werkzeug:
  - 0.16.*
wheel:
  - 0.36*
xorg_x11_proto_devel_rhel7_s390x:
  - 2018.4.*
zipp:
  - 3.1.*
