name: Open-CE PR Tests for Conda recipe

on:
  pull_request:
    branches: [main]

jobs:
  required_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: "3.7"
      - name: Build and install the conda package
        id: build_install
        run: |
            sh open-ce/packaging_scripts/create_conda_package.sh
            conda list open-ce


  optional_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: "3.7"
      - name: Set the recipe config file value
        id: set_env
        run: |
            echo "OPENCE_RECIPE_CONFIG_FILE"\
                 "=open-ce/conda/config/build-config.yaml" >> $GITHUB_ENV
      - uses: open-ce/open-ce/.github/actions/feedstock-optional-pr@main
